name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/gcp-service-template:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Check out the Ansible configuration repository
      - name: Checkout ansible config repo
        uses: actions/checkout@v4
        with:
          repository: mfcarroll/gcp-server-config
          token: ${{ secrets.GH_PAT }} # Use a PAT to access the private repo

      # Run the Ansible playbook
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          inventory: inventory
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}