name: Build, Push, and Deploy

on:
  push:
    branches: ["main"]

jobs:
  call-reusable-workflow:
    uses: mfcarroll/gcp-server-config/.github/workflows/reusable-deploy.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      appname: template
    secrets:
      inherit